spring:
  datasource:
    url: jdbc:mysql://localhost/experimental-schema?autoReconnect=true&useSSL=false
    username: root
    password: Osbo_789
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    Show-sql: true

  thymeleaf:
    cache: false

debug: false

google:
  client:
    clientId: 964513099769-moqm18t6ftg0rhflraouctiunitv6sjv.apps.googleusercontent.com
    clientSecret: AfBOG29GRoCyWTUpe8v3mgA3
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
