spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umspreadsheet_dev?autoReconnect=true&useSSL=false&serverTimezone=America/Detroit&allowPublicKeyRetrieval=true
    username: umspreadsheet
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    Show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates

debug: false
