spring:
  application:
    name: umspreadsheet
  datasource:
    url: jdbc:mysql://localhost/umspreadsheet?autoReconnect=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    Show-sql: false
  thymeleaf:
    cache: false
  social:
      facebook:
        app-id: 1121868971273792
        app-secret: secret
      twitter:
        app-id: Vjz71FPnLEJMwpjAIfvpf1dAl
        app-secret: secret
      google:
        app-id: 964513099769-moqm18t6ftg0rhflraouctiunitv6sjv.apps.googleusercontent.com
        app-secret: secret
  mail:
    host: smtp.gmail.com
    username: andrewosborn93@gmail.com
    password: password
    port: 587
    properties:
        mail:
            smtp:
                starttls:
                    enable: true
    test-connection: false

debug: false

CLOUDINARY_URL: cloudinary://619785555338512:1RQzh1bhPGp0r_1kLZvnHZ8LBYg@umspreadsheet
