spring:
  application:
    name: umspreadsheet
  datasource:
    url: jdbc:mysql://localhost/umspreadsheet_dev?autoReconnect=true&useSSL=false
    username: root
    password: Osbo_789
  jpa:
    hibernate:
      ddl-auto: update
    Show-sql: false
  thymeleaf:
    cache: false
  social:
      facebook:
        app-id: 1121868971273792
        app-secret: 401ec59dd72250d20f1035df912af9a6
      twitter:
        app-id: Vjz71FPnLEJMwpjAIfvpf1dAl
        app-secret: AqG4qwAxWEV9O0OYce8IDtDk2Xe8CwdYchYONj2TtKwWpAGOmY
      google:
        app-id: 964513099769-moqm18t6ftg0rhflraouctiunitv6sjv.apps.googleusercontent.com
        app-secret: AfBOG29GRoCyWTUpe8v3mgA3
  mail:
    host: smtp.gmail.com
    username: andrewosborn93@gmail.com
    password: Osbo_7891011
    port: 587
    properties:
        mail:
            smtp:
                starttls:
                    enable: true
    test-connection: true

debug: false

CLOUDINARY_URL: cloudinary://619785555338512:1RQzh1bhPGp0r_1kLZvnHZ8LBYg@umspreadsheet