spring:

  datasource:
    url: jdbc:mysql://localhost/ums_dummy?autoReconnect=true&useSSL=false
    username: root
    password: Osbo_789
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    Show-sql: false

  thymeleaf:
    cache: false

debug: false
